INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (10, 'Adm', 200, 1700);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (20, 'Mar', 201, 1800);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (30, 'Pur', 114, 1700);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (40, 'Hum', 203, 2400);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (50, 'Shi', 121, 1500);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (60, 'IT', 103, 1400);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (70, 'Pub', 204, 2700);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (80, 'Sal', 145, 2500);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (90, 'Exe', 100, 1700);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (100, 'Fin', 108, 1700);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (110, 'Acc', 205, 1700);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (120, 'Tre', NULL, 1700);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (130, 'Cor', NULL, 1700);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (140, 'Con', NULL, 1700);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (150, 'Sha', NULL, 1700);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (160, 'Ben', NULL, 1700);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (170, 'Man', NULL, 1700);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (180, 'Con', NULL, 1700);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (190, 'Con', NULL, 1700);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (200, 'Ope', NULL, 1700);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (210, 'IT ', NULL, 1700);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (220, 'NOC', NULL, 1700);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (230, 'IT ', NULL, 1700);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (240, 'Gov', NULL, 1700);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (250, 'Ret', NULL, 1700);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (260, 'Rec', NULL, 1700);
INSERT INTO `departments`(`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (270, 'Pay', NULL, 1700);
