INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (103, 'Hunold', 60, 1400, 'Southlake');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (104, 'Ernst', 60, 1400, 'Southlake');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (105, 'Austin', 60, 1400, 'Southlake');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (106, 'Pataballa', 60, 1400, 'Southlake');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (107, 'Lorentz', 60, 1400, 'Southlake');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (120, 'Weiss', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (121, 'Fripp', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (122, 'Kaufling', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (123, 'Vollman', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (124, 'Mourgos', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (125, 'Nayer', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (126, 'Mikkilineni', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (127, 'Landry', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (128, 'Markle', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (129, 'Bissot', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (130, 'Atkinson', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (131, 'Marlow', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (132, 'Olson', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (133, 'Mallin', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (134, 'Rogers', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (135, 'Gee', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (136, 'Philtanker', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (137, 'Ladwig', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (138, 'Stiles', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (139, 'Seo', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (140, 'Patel', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (141, 'Rajs', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (142, 'Davies', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (143, 'Matos', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (144, 'Vargas', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (180, 'Taylor', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (181, 'Fleaur', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (182, 'Sullivan', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (183, 'Geoni', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (184, 'Sarchand', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (185, 'Bull', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (186, 'Dellinger', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (187, 'Cabrio', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (188, 'Chung', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (189, 'Dilly', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (190, 'Gates', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (191, 'Perkins', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (192, 'Bell', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (193, 'Everett', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (194, 'McCain', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (195, 'Jones', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (196, 'Walsh', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (197, 'Feeney', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (198, 'OConnell', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (199, 'Grant', 50, 1500, 'South San Francisco');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (200, 'Whalen', 10, 1700, 'Seattle');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (114, 'Raphaely', 30, 1700, 'Seattle');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (115, 'Khoo', 30, 1700, 'Seattle');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (116, 'Baida', 30, 1700, 'Seattle');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (117, 'Tobias', 30, 1700, 'Seattle');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (118, 'Himuro', 30, 1700, 'Seattle');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (119, 'Colmenares', 30, 1700, 'Seattle');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (100, 'K_ing', 90, 1700, 'Seattle');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (101, 'Kochhar', 90, 1700, 'Seattle');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (102, 'De Haan', 90, 1700, 'Seattle');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (108, 'Greenberg', 100, 1700, 'Seattle');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (109, 'Faviet', 100, 1700, 'Seattle');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (110, 'Chen', 100, 1700, 'Seattle');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (111, 'Sciarra', 100, 1700, 'Seattle');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (112, 'Urman', 100, 1700, 'Seattle');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (113, 'Popp', 100, 1700, 'Seattle');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (205, 'Higgins', 110, 1700, 'Seattle');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (206, 'Gietz', 110, 1700, 'Seattle');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (201, 'Hartstein', 20, 1800, 'Toronto');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (202, 'Fay', 20, 1800, 'Toronto');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (203, 'Mavris', 40, 2400, 'London');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (145, 'Russell', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (146, 'Partners', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (147, 'Errazuriz', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (148, 'Cambrault', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (149, 'Zlotkey', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (150, 'Tucker', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (151, 'Bernstein', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (152, 'Hall', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (153, 'Olsen', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (154, 'Cambrault', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (155, 'Tuvault', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (156, 'K_ing', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (157, 'Sully', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (158, 'McEwen', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (159, 'Smith', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (160, 'Doran', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (161, 'Sewall', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (162, 'Vishney', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (163, 'Greene', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (164, 'Marvins', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (165, 'Lee', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (166, 'Ande', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (167, 'Banda', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (168, 'Ozer', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (169, 'Bloom', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (170, 'Fox', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (171, 'Smith', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (172, 'Bates', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (173, 'Kumar', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (174, 'Abel', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (175, 'Hutton', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (176, 'Taylor', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (177, 'Livingston', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (179, 'Johnson', 80, 2500, 'Oxford');
INSERT INTO `em_dep_loc`(`employee_id`, `last_name`, `department_id`, `location_id`, `city`) VALUES (204, 'Baer', 70, 2700, 'Munich');
